import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ShieldAlert, ShieldCheck, User, LogIn, Lock, ArrowRight, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import Input from '@/components/ui/Input';
import Button from '@/components/ui/Button';
import { PwaInstallPrompt } from '@/components/pwa/PwaInstallPrompt';
import { useVerifyActivationTokenQuery, useCompleteAccountSetupMutation } from '@/libs/state/redux/api/userApi';
import { useAppDispatch } from '@/libs/state/redux/hooks';
import { setAuthSession } from '@/libs/state/redux/slices/user/auth.slice';
import { capitalizeWords } from '@/libs/utils/text';
import { APP_ROUTES } from '@/config/routes';

/**
 * Public account activation and signup view.
 * Accessed exclusively with a signed token generated by a church volunteer/server.
 * Allows the pre-registered user to set their password and optional email.
 *
 * @returns {JSX.Element} Account activation form or authorization guard screen.
 */
const AccountSignupPublicView: React.FC = () => {
  const { t } = useTranslation(['auth', 'common']);
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  const [searchParams] = useSearchParams();
  const token = searchParams.get('token') || '';

  const {
    data: verifyResult,
    isLoading: isVerifying,
    isError: isTokenError,
  } = useVerifyActivationTokenQuery(
    { token },
    { skip: !token }
  );

  const [completeSetup, { isLoading: isSubmitting }] = useCompleteAccountSetupMutation();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  // Prefill email if user already has one on record
  useEffect(() => {
    if (verifyResult?.user?.email) {
      setEmail(verifyResult.user.email);
    }
  }, [verifyResult]);

  const clearError = (field: string) => {
    setFieldErrors((prev) => {
      if (!prev[field]) return prev;
      const next = { ...prev };
      delete next[field];
      return next;
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const errors: Record<string, string> = {};

    if (email.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
      errors.email = t('auth:signup.email_invalid');
    }

    if (!password || password.length < 6) {
      errors.password = t('auth:signup.password_min_length');
    }

    if (password !== confirmPassword) {
      errors.confirmPassword = t('auth:signup.passwords_must_match');
    }

    if (Object.keys(errors).length > 0) {
      setFieldErrors(errors);
      const firstError = errors.password || errors.confirmPassword || errors.email;
      toast.error(firstError);
      return;
    }

    try {
      const response = await completeSetup({
        token,
        email: email.trim() || undefined,
        password,
      }).unwrap();

      if (response.success) {
        if (response.token && response.user) {
          dispatch(
            setAuthSession({
              token: response.token,
              refreshToken: response.refreshToken,
              user: response.user,
            })
          );
        }
        toast.success(t('auth:signup.toast_success'));
        navigate(APP_ROUTES.public.signupConfirmation, { replace: true });
      }
    } catch (err: unknown) {
      const errorResponse = err as { data?: { message?: string }; message?: string };
      const errorMessage =
        errorResponse?.data?.message ||
        errorResponse?.message ||
        t('auth:signup.toast_error');
      toast.error(errorMessage);
    }
  };

  // State 1: Verifying token in progress
  if (token && isVerifying) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-6 text-center">
        <div className="w-16 h-16 rounded-full bg-primary/10 text-primary flex items-center justify-center mb-4">
          <Loader2 size={32} className="animate-spin text-primary" />
        </div>
        <p className="text-sm font-semibold text-gray-600">
          {t('common:states.loading')}
        </p>
      </div>
    );
  }

  // State 2: No token, invalid token or expired token
  if (!token || isTokenError || !verifyResult?.valid) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-6 text-center animate-in fade-in duration-300">
        <div className="w-full max-w-sm bg-white p-7 rounded-3xl shadow-sm border border-gray-100 flex flex-col items-center gap-4">
          <div className="w-16 h-16 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center border-2 border-amber-200 shadow-inner">
            <ShieldAlert size={32} />
          </div>

          <div>
            <h2 className="text-lg font-bold text-gray-800">
              {t('auth:signup.unauthorized_title')}
            </h2>
            <p className="text-xs text-gray-500 mt-2 leading-relaxed">
              {t('auth:signup.unauthorized_desc')}
            </p>
          </div>

          <div className="w-full pt-3 border-t border-gray-100 mt-2 flex flex-col gap-2">
            <Button
              type="button"
              variant="default"
              onClick={() => navigate(APP_ROUTES.auth.login)}
              block
              className="py-3 text-sm font-semibold rounded-xl flex items-center justify-center gap-2"
            >
              <LogIn size={16} />
              {t('auth:signup.go_to_login')}
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // State 2.5: User already has an active account with password configured (signup not allowed)
  if (verifyResult.alreadyHasAccount || verifyResult.user?.hasPassword) {
    const existingUser = verifyResult.user;
    const existingName = `${capitalizeWords(existingUser.firstName)} ${capitalizeWords(existingUser.lastName)}`.trim();
    const existingDoc = `${existingUser.nationalIdType || 'CC'}: ${existingUser.nationalId || ''}`;

    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4 sm:p-6 text-center animate-in fade-in duration-300">
        <div className="w-full max-w-md bg-white p-6 sm:p-7 rounded-3xl shadow-sm border border-gray-100 flex flex-col items-center gap-4">
          <div className="w-16 h-16 rounded-full bg-blue-50 text-primary flex items-center justify-center border-2 border-blue-200 shadow-inner">
            <ShieldCheck size={34} />
          </div>

          <div>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-[11px] font-bold uppercase tracking-wider mb-2">
              {t('auth:signup.already_has_account_badge')}
            </span>
            <h2 className="text-lg font-bold text-gray-800">
              {t('auth:signup.already_has_account_title')}
            </h2>
            <p className="text-xs text-gray-500 mt-2 leading-relaxed">
              {t('auth:signup.already_has_account_desc')}
            </p>
          </div>

          <div className="w-full bg-slate-50 border border-slate-100 rounded-2xl p-3.5 flex flex-col items-center gap-1 text-center">
            <p className="text-xs font-bold text-gray-800">{existingName}</p>
            <p className="text-[11px] font-medium text-gray-500">{existingDoc}</p>
            {existingUser.username && (
              <p className="text-[11px] font-semibold text-primary font-mono mt-0.5">
                @{existingUser.username}
              </p>
            )}
          </div>

          {/* PWA Installation Section */}
          <div className="w-full pt-1">
            <PwaInstallPrompt />
          </div>

          <div className="w-full pt-2 flex flex-col gap-2">
            <Button
              type="button"
              variant="primary"
              onClick={() => navigate(APP_ROUTES.auth.login)}
              block
              className="py-3 text-sm font-semibold rounded-xl flex items-center justify-center gap-2"
            >
              <LogIn size={16} />
              {t('auth:signup.already_has_account_action')}
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // State 3: Valid token with user information ready to activate
  const user = verifyResult.user;
  const fullName = `${capitalizeWords(user.firstName)} ${capitalizeWords(user.lastName)}`.trim();
  const documentLabel = `${user.nationalIdType || 'CC'}: ${user.nationalId || ''}`;

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center px-4 py-8 animate-in fade-in duration-300">
      <div className="w-full max-w-md flex flex-col items-center gap-5">
        {/* Header Logo */}
        <div className="flex flex-col items-center mb-1">
          <img src="/logo-iglekids.png" alt="Logo" className="w-48 h-auto drop-shadow-xs" />
        </div>

        {/* Card Form */}
        <div className="w-full bg-white p-6 sm:p-7 rounded-3xl shadow-sm border border-gray-100 flex flex-col gap-5">
          {/* Title and subtitle */}
          <div className="text-center">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary/10 text-primary text-[11px] font-bold uppercase tracking-wider mb-2">
              <ShieldCheck size={14} />
              {t('auth:signup.badge')}
            </span>
            <h2 className="text-xl font-bold text-gray-800">
              {t('auth:signup.title')}
            </h2>
            <p className="text-xs text-gray-500 mt-1 leading-relaxed">
              {t('auth:signup.subtitle')}
            </p>
          </div>

          {/* Authorized Person Box */}
          <div className="bg-blue-50/70 border border-blue-100 rounded-2xl p-4 flex items-center gap-3.5 text-left">
            <div className="w-11 h-11 rounded-full bg-primary/15 text-primary flex items-center justify-center shrink-0">
              <User size={22} />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold uppercase tracking-wider text-primary">
                {t('auth:signup.verified_person_badge')}
              </p>
              <h3 className="text-sm font-bold text-gray-800 truncate mt-0.5">
                {fullName}
              </h3>
              <p className="text-xs text-gray-500 font-medium">
                {documentLabel}
              </p>
            </div>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="flex flex-col gap-4 text-left">
            {/* Optional Email */}
            <Input
              label={t('auth:signup.email_label')}
              type="email"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
                clearError('email');
              }}
              placeholder={t('auth:signup.email_placeholder')}
              autoComplete="email"
              error={fieldErrors.email}
              className="placeholder:text-gray-400"
            />

            {/* Password */}
            <Input
              label={t('auth:signup.password_label')}
              type="password"
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                clearError('password');
              }}
              placeholder={t('auth:signup.password_placeholder')}
              autoComplete="new-password"
              required
              error={fieldErrors.password}
              className="placeholder:text-gray-400"
            />

            {/* Confirm Password */}
            <Input
              label={t('auth:signup.confirm_password_label')}
              type="password"
              value={confirmPassword}
              onChange={(e) => {
                setConfirmPassword(e.target.value);
                clearError('confirmPassword');
              }}
              placeholder={t('auth:signup.confirm_password_placeholder')}
              autoComplete="new-password"
              required
              error={fieldErrors.confirmPassword}
              className="placeholder:text-gray-400"
            />

            <Button
              type="submit"
              variant="primary"
              loading={isSubmitting}
              block
              className="mt-2 py-3.5 font-bold text-sm rounded-xl shadow-xs flex items-center justify-center gap-2"
            >
              <Lock size={16} />
              {t('auth:signup.submit_button')}
              <ArrowRight size={16} />
            </Button>
          </form>

          {/* Footer Link to Login */}
          <div className="pt-2 border-t border-gray-100 flex justify-center">
            <button
              type="button"
              onClick={() => navigate(APP_ROUTES.auth.login)}
              className="text-xs font-semibold text-gray-500 hover:text-primary transition-colors flex items-center gap-1.5 py-1"
            >
              <LogIn size={14} />
              {t('auth:signup.go_to_login')}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AccountSignupPublicView;
